### ISSUE TITLE
Can't run the game on Mac m1 

### ISSUE THREAD

**Issue by foobnix** [defold/sample-rive-game#2]
<img width="1861" alt="Screenshot 2023-08-10 at 10 53 19" src="https://github.com/defold/sample-rive-game/assets/432440/a2f96b83-7ad9-49b4-bb13-c903831710fd">

/defold-rive/src/res_rive_scene.cpp
	Line 49: cannot initialize a parameter of type 'void *' with an lvalue of type 'dmGraphics::HTexture' (aka 'unsigned long long')
            dmResource::Release(factory, resource->m_Texture);
                                         ^~~~~~~~~~~~~~~~~~~

/defold-rive/src/res_rive_scene.cpp
	Line 49: passing argument to parameter 'resource' here
    void Release(HFactory factory, void* resource);
                                         ^

**Comment by JCash** [comment]
Thanks!
It looks like we need to update the rive extension dependency.
